version: "3.9"
services:
  php-apache-environment:
    container_name: randiko-php-apache
    build:
      context: ./public
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html/
      - ./app:/var/www/html/app
    ports:
      - "6969:80"
  db:
    container_name: randiko_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    depends_on:
      - db
volumes:
  db: {}
